version: "3.1"

services:

  tor:
    image: vx/tor-gate
    build: .
    restart: always
        
    #network_mode: host
    ports:
      - "9050:9050"

    # Keep keys in volumes
    #volumes:
      #- "./data/tor:/etc/tor"
      #- "./data/tor-keys/:/var/lib/tor/hidden_service/"
      #- "tor-keys:/var/lib/tor/hidden_service/"

volumes:
  tor-keys:
     driver: local


